export const PAGE_CONTAINER = 'mx-auto w-full max-w-[79.5rem] px-4 sm:px-6 lg:px-8'
export const PAGE_CONTAINER_SPACED = 'mx-auto w-full max-w-[79.5rem] px-4 py-14 sm:px-6 lg:px-8 lg:py-18'
export const PAGE_HERO = 'border-b border-ht-silver bg-gradient-to-br from-white via-ht-soft-blue to-cyan-50'
export const PAGE_SECTION = 'border-y border-ht-silver bg-white py-14 lg:py-18'
export const PAGE_SECTION_SOFT = 'border-b border-ht-silver bg-ht-soft-blue/20 py-14 lg:py-18'
export const PAGE_PANEL = 'ht-motion-smooth rounded-[2rem] border border-ht-silver bg-white shadow-[0_18px_42px_-34px_rgba(5,42,74,0.45)]'
export const PAGE_PANEL_SOFT =
  'ht-motion-smooth rounded-[2rem] border border-cyan-100 bg-white shadow-[0_24px_60px_-34px_rgba(5,42,74,0.45)]'
export const PAGE_PANEL_GRADIENT =
  'ht-motion-smooth rounded-[2rem] border border-ht-silver bg-gradient-to-br from-white via-ht-soft-blue to-cyan-50 shadow-[0_22px_52px_-34px_rgba(5,42,74,0.45)]'
export const PAGE_CARD = 'ht-motion-smooth rounded-2xl border border-ht-silver bg-white shadow-[0_18px_42px_-34px_rgba(5,42,74,0.45)]'
export const PAGE_CARD_SOFT = 'ht-motion-smooth rounded-2xl border border-ht-silver bg-ht-soft-blue/20 shadow-[0_16px_34px_-30px_rgba(5,42,74,0.45)]'
export const PAGE_IMAGE_FRAME = 'overflow-hidden rounded-[1.5rem] border border-ht-silver bg-ht-soft-blue/20'
export const PAGE_IMAGE_FRAME_SOFT = 'overflow-hidden rounded-[1.5rem] border border-cyan-100 bg-white'
export const PAGE_ICON_CIRCLE = 'inline-flex h-[2.65rem] w-[2.65rem] items-center justify-center rounded-full bg-ht-soft-blue text-ht-cyan-700 shadow-sm ring-1 ring-cyan-100'
export const PAGE_BADGE = 'inline-flex rounded-full bg-cyan-100 px-[0.8rem] py-[0.4rem] text-[0.75rem] font-semibold uppercase tracking-[0.12em] text-ht-navy-700'
export const PAGE_PILL = 'inline-flex rounded-full bg-cyan-50 px-[0.7rem] py-[0.4rem] text-sm font-semibold text-ht-navy-700'
